// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6TL-gZd05wLziXWHs8cQuVCCZ2BdKzas',
    appId: '1:585762391028:web:04cc9e017b8b0eef742fa1',
    messagingSenderId: '585762391028',
    projectId: 'hiphab-6a19f',
    authDomain: 'hiphab-6a19f.firebaseapp.com',
    storageBucket: 'hiphab-6a19f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_MOyaCWE32NfvPcPyxrjQcG5ohcB6FbQ',
    appId: '1:585762391028:android:4ff2a406c73d8a65742fa1',
    messagingSenderId: '585762391028',
    projectId: 'hiphab-6a19f',
    storageBucket: 'hiphab-6a19f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhh5kogbU1_4IP8L2kxdCoZ165WZiww6E',
    appId: '1:585762391028:ios:c1ff6de127090f0c742fa1',
    messagingSenderId: '585762391028',
    projectId: 'hiphab-6a19f',
    storageBucket: 'hiphab-6a19f.appspot.com',
    iosBundleId: 'com.example.therapy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhh5kogbU1_4IP8L2kxdCoZ165WZiww6E',
    appId: '1:585762391028:ios:c1ff6de127090f0c742fa1',
    messagingSenderId: '585762391028',
    projectId: 'hiphab-6a19f',
    storageBucket: 'hiphab-6a19f.appspot.com',
    iosBundleId: 'com.example.therapy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6TL-gZd05wLziXWHs8cQuVCCZ2BdKzas',
    appId: '1:585762391028:web:f27bdcf56e96d405742fa1',
    messagingSenderId: '585762391028',
    projectId: 'hiphab-6a19f',
    authDomain: 'hiphab-6a19f.firebaseapp.com',
    storageBucket: 'hiphab-6a19f.appspot.com',
  );
}
